name: aika_assistant
description: Aika - Anime AI Assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Speech & Voice
  speech_to_text: ^6.6.2
  flutter_tts: ^4.0.2
  
  # Animations
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  
  # UI & Effects
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  
  # Storage & State
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  
  # Utils
  permission_handler: ^11.3.1
  battery_plus: ^6.0.2
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.0
  android_intent_plus: ^4.0.2
  torch_light: ^1.0.1
  volume_controller: ^2.0.7
  
  # HTTP
  http: ^1.2.1
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/aika_chibi.png
    - assets/images/aika_think.png
    - assets/images/aika_dance4.png
    - assets/images/aika_dance16.png
    - assets/images/aika_dance15.png
    - assets/images/aika_dance14.png
    - assets/images/aika_dance13.png
    - assets/images/aika_dance12.png
    - assets/images/aika_dance11.png
    - assets/images/aika_dance10.png
    - assets/images/aika_dance9.png
    - assets/images/aika_dance8.png
    - assets/images/aika_dance7.png
    - assets/images/aika_dance6.png
    - assets/images/aika_dance5.png
    - assets/images/aika_dance3.png
    - assets/images/aika_dance2.png
    - assets/images/aika_dance1.png
    - assets/images/aika_listen.png
    - assets/images/aika_wave.png
    - assets/images/aika_idle.png
    - assets/images/
    - assets/animations/
    - assets/models/

